### ISSUE TITLE
'gbk' codec can't encode character '\u2022' in position 13643919: illegal multibyte sequence

### ISSUE THREAD

**Issue by Skypow2012** [haochengxia/vscode-pydata-viewer#12]

**Comment by haochengxia** [comment]
It appears that you attempted to open a file using the 'gbk' encoding, but the file contains characters that are not compatible with 'gbk'. To fix it, we can set encoding by `open('filename.txt', encoding='utf-8')`.

**Comment by haochengxia** [comment]
In addition, since the data types supported by the extension are all stored in binary format, there is no encoding problem in theory. If you need further help, please provide a way to reproduce the problem, thank you!
