### ISSUE TITLE
[Proposal / Feature request] Support ${workspaceFolder} (and some reference variable) for pythonPath and scriptPath config

### ISSUE THREAD

**Issue by Take-Me1010** [haochengxia/vscode-pydata-viewer#21]
Thank you for your great extention.

The config for `pythonPath` and `scriptPath` is only supported absolute-path style, right?
It would be good if I can use "${workspaceWolder}" for path config as follows:

```json
{
    "vscode-pydata-viewer.scriptPath": "${workspaceFolder}/read_files.py",
}
```

With respect to `scriptPath` config, I think inserting some codes to replace variable around [line 139 in pydataPreview.ts](https://github.com/haochengxia/vscode-pydata-viewer/blob/a861610cd9f40075fec6431706a8b078f7d8d899/src/pydataPreview.ts#L139) resolves my concern: 

```typescript
const workspace = vscode.workspace.getWorkspaceFolder(vscode.Uri.file(resourcePath));
scriptPath = scriptPath.replace('${workspaceFolder}', workspace.uri.fsPath);    // note  `scriptPath` is a const variable, so there is a need to write more beautiful code...
```

PS: This may relate #3 . In addition, this feature can resolve some problems like #19 more easily.

**Comment by haochengxia** [comment]
Thanks for your proposal! The feat is added in [the latest commit](https://github.com/haochengxia/vscode-pydata-viewer/commit/2038518a3d0536c84916501be68e8c9bacf82097). Please feel free to provide more details and suggestions if you have any further concerns.

**Comment by Take-Me1010** [comment]
Thank you for your quick reply and coding!

It seems perfect at a glance. 
However, one concern remains.
If this feature for `scriptPath` is released, users may think ${workspaceFolder} can also be used for `pythonPath`, which may cause confusion.
So supporting ${workspaceFolder} for `pythonPath` is also crucial, I believe.
These features will bring comfortable experience in a python virtual environment as follows:
```json
{
    "vscode-pydata-viewer.scriptPath": "${workspaceFolder}/read_files.py",
    "vscode-pydata-viewer.pythonPath": "${workspaceFolder}/.venv/Scripts/python.exe",
}
```

**Comment by haochengxia** [comment]
Thank you for your comment. I sincerely appreciate it. I will revise the code soon before the next version update.
