### ISSUE TITLE
Uncaught Errors

### ISSUE THREAD

**Issue by zhaoyu-18** [haochengxia/vscode-pydata-viewer#33]
Hi, I can't open files in formats such as npy. Every time I try to open, it displays Uncaught Errors (1) at Runtime Status: Cannot read properties of null (reading 'length'). Why is that? Thank you.

**Comment by zhaoyu-18** [comment]
I eventually found out that there was a problem with python's system environment path, and after modifying it, it worked fine.

**Comment by AClon314** [comment]
> I eventually found out that there was a problem with python's system environment path, and after modifying it, it worked fine.

Hi @zhaoyu-18 , how do you modify your python path? I use mamba/conda on Linux and I encounter this error in output_tab/extension_host:
```log
2025-03-12 21:40:15.341 [error] TypeError: Cannot read properties of null (reading 'length')
    at /home/n/.vscode/extensions/percy.vscode-pydata-viewer-0.0.13/out/pydataPreview.js:121:35
    at PythonShell._endCallback (/home/n/.vscode/extensions/percy.vscode-pydata-viewer-0.0.13/node_modules/python-shell/index.js:254:20)
    at terminateIfNeeded (/home/n/.vscode/extensions/percy.vscode-pydata-viewer-0.0.13/node_modules/python-shell/index.js:209:39)
    at ChildProcess.<anonymous> (/home/n/.vscode/extensions/percy.vscode-pydata-viewer-0.0.13/node_modules/python-shell/index.js:182:13)
    at ChildProcess.emit (node:events:518:28)
    at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
    at Process.callbackTrampoline (node:internal/async_hooks:130:17)
```

My current config:
```
Vscode-pydata-viewer: Python Path
/home/n/miniforge3/envs/mocap/bin/python

Vscode-pydata-viewer: Script Path
default
```

**Comment by zhaoyu-18** [comment]
> > I eventually found out that there was a problem with python's system environment path, and after modifying it, it worked fine.
> 
> Hi [@zhaoyu-18](https://github.com/zhaoyu-18) , how do you modify your python path? I use mamba/conda on Linux and I encounter this error in output_tab/extension_host:
> 
> ```
> 2025-03-12 21:40:15.341 [error] TypeError: Cannot read properties of null (reading 'length')
>     at /home/n/.vscode/extensions/percy.vscode-pydata-viewer-0.0.13/out/pydataPreview.js:121:35
>     at PythonShell._endCallback (/home/n/.vscode/extensions/percy.vscode-pydata-viewer-0.0.13/node_modules/python-shell/index.js:254:20)
>     at terminateIfNeeded (/home/n/.vscode/extensions/percy.vscode-pydata-viewer-0.0.13/node_modules/python-shell/index.js:209:39)
>     at ChildProcess.<anonymous> (/home/n/.vscode/extensions/percy.vscode-pydata-viewer-0.0.13/node_modules/python-shell/index.js:182:13)
>     at ChildProcess.emit (node:events:518:28)
>     at Process.ChildProcess._handle.onexit (node:internal/child_process:293:12)
>     at Process.callbackTrampoline (node:internal/async_hooks:130:17)
> ```
> 
> My current config:
> 
> ```
> Vscode-pydata-viewer: Python Path
> /home/n/miniforge3/envs/mocap/bin/python
> 
> Vscode-pydata-viewer: Script Path
> default
> ```

Hi, I'm on Windows, so I don't really know how to fix this on Linux.

**Comment by AClon314** [comment]
I found an alternative solution, use vscode offical extension: [Data Wrangler](https://code.visualstudio.com/docs/datascience/data-wrangler), with this [`.py` file](https://github.com/AClon314/mocap-wrapper/blob/45d3a1db562a49b7fc6cecfba3ef80603cf0bdb6/src/mocap_wrapper/script/data_viewer.py) and this [`.ipynb` notebook](https://github.com/AClon314/mocap-wrapper/blob/45d3a1db562a49b7fc6cecfba3ef80603cf0bdb6/tests/data_viewer.ipynb)
![vscode ext](https://code.visualstudio.com/assets/docs/datascience/data-wrangler/full-dw-loop.gif)
