### ISSUE TITLE
No module named 'torch'

### ISSUE THREAD

**Issue by Fizinftop99** [haochengxia/vscode-pydata-viewer#5]
`No module named 'torch'` in .pth file after `PATH = './cifar_net.pth'
torch.save(net.state_dict(), PATH)`

**Comment by haochengxia** [comment]
Thanks for your issue. This error may cause by the data object being torch builtin type. I will fix it as soon as possible.

**Comment by Aldlevine** [comment]
I had a similar issue with torch installed in .venv, but not globally. I fixed it by changing the python-path setting to the .venv version of python (appears to need absolute path).
