### ISSUE TITLE
Support for conda environment

### ISSUE THREAD

**Issue by FakeTrader** [haochengxia/vscode-pydata-viewer#7]
I use conda base as the default python interpreter and have pytorch installed in dedicated envs incase of conflicts. Is there any way I can select the interperter?

**Comment by haochengxia** [comment]
How about the solution that adds a custom config option to select a python interpreter? I can be supported in the next version if needed.

**Comment by FakeTrader** [comment]
It is fine as a workaround.

**Comment by haochengxia** [comment]
`pythonPath` has been supported to customize in v0.0.5 now. 🎉
